---
namespace: threescale
sso_project: rh-sso
backend_project: international
apicurio_project: apicurio
gogs_project: gogs
microcks_project: microcks
jenkins_project: jenkins
sso_version: ose-v1.4.9
ocp_domain: 3901.open.redhat.com
ocp_apps_domain: apps.3901.open.redhat.com
usersno: 20
threescale: true
apicurio: true
gogs: true
microcks: true
sso: true
backend: true
user_projects: true
configure_only: false
create_tenants: true
create_realms: true
